[project]
name = "Pi-3D-Tracking"
version = "0.1.0"
dependencies = [
    "torch==2.5.1",
    "torchvision==0.20.1",
    "numpy==1.26.4",
    "scipy",
    "pillow",
    "opencv-python",
    "plyfile",
    "huggingface_hub",
    "safetensors",
    "tqdm",
]