# Warmup + Cosine Annealing learning rate scheduler
# Standard schedule for transformer training

_target_: transformers.get_cosine_schedule_with_warmup

# Warmup phase: linear increase from 0 to lr
num_warmup_steps: ${training.warmup_steps}

# Total training steps
num_training_steps: ${training.total_steps}

# Minimum learning rate at end of cosine decay
# Set to 0.0 for full decay, or small value (e.g., 1e-6) for minimum lr
num_cycles: 0.5  # 0.5 = standard cosine, 1.0 = full cosine cycle

# Schedule:
# Steps 0 to warmup_steps: Linear warmup from 0 to lr
# Steps warmup_steps to total_steps: Cosine decay from lr to min_lr
