# MTMC Tracking 2025 dataset configuration

# Dataset paths
data_root: ./data/MTMC_Tracking_2025
train_split: train
val_split: val
test_split: test

# Class information
num_classes: 3
class_names:
  - Forklift
  - NovaCarter
  - Transporter

# Class IDs (0-indexed)
class_ids:
  Forklift: 0
  NovaCarter: 1
  Transporter: 2

# Data loading
num_cameras: -1  # -1 = use all available cameras, or specify number
image_size: [518, 518]  # [H, W] - resized from original 1080x1920

# Data augmentation (for training)
augmentation:
  # Random horizontal flip
  hflip_prob: 0.5

  # Random color jitter
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1

  # Random crop/resize
  random_crop: false

  # Normalization (ImageNet stats, handled by Pi3)
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Pi3 transform settings
pi3_transform:
  pixel_limit: 255000  # Limit total pixels per sample for memory efficiency

# Dataset statistics
scenes:
  train:
    - warehouse
  val:
    - hospital
    - lab
    - warehouse
  test:
    - warehouse

# Object statistics (approximate)
avg_objects_per_frame: 5
max_objects_per_frame: 10

# Notes:
# - Multi-camera synchronized views
# - 3D annotations in world coordinates
# - 2D bounding boxes per camera view
# - Object instance IDs for tracking
